name: ci

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 13 * * *"

jobs:
  check-for-new-cascadia:
    runs-on: ubuntu-20.04
    outputs:
      tag_name: ${{ env.CASCADIATAG }}
      tag_exists: ${{ steps.check_tag.outputs.exists }}
  
    steps:
    - name: Fetch latest release of Cascadia Code
      uses: octokit/request-action@v2.x
      id: get_latest_release
      with:
        route: GET /repos/{owner}/{repo}/releases/latest
        owner: microsoft
        repo: cascadia-code
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Get the latest Cascadia tag
      run: |
        echo "CASCADIATAG=${{ fromJson(steps.get_latest_release.outputs.data).tag_name }}" >> $GITHUB_ENV
        echo "Latest Cascadia tag is ${{ env.CASCADIATAG }}"
    - name: Check if tag exists
      uses: mukunku/tag-exists-action@v1.0.0
      id: check_tag
      with: 
        tag: ${{ env.CASCADIATAG }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  build-and-release:
    needs: check-for-new-cascadia
    if: ${{ github.event_name != 'schedule' || needs.check-for-new-cascadia.outputs.tag_exists != 'true' }}
    runs-on: ubuntu-18.04
    env:
      NERDFONTVERS: v2.1.0

    steps:
    - uses: actions/checkout@v2
    - name: Download latest version of Cascadia
      run: |
        CASCADIAVERS=`curl -L 'https://github.com/microsoft/cascadia-code/releases/latest' | grep CascadiaCode | sed 's!\(.*/microsoft/cascadia-code/releases/download/\([^"]*\).*\|.*span.*\)!\2!'`
        echo Downloading ${CASCADIAVERS}
        curl -L https://github.com/microsoft/cascadia-code/releases/download/${CASCADIAVERS}  -O
        unzip CascadiaCode*.zip
    - name: Install FontForge
      run: |
        sudo add-apt-repository ppa:fontforge/fontforge -y -u;
        sudo apt-get install fontforge -y;
    - name: Download and patch Font Patcher
      run: |
        curl -L https://raw.githubusercontent.com/ryanoasis/nerd-fonts/${NERDFONTVERS}/font-patcher --output font-patcher
        patch font-patcher 0001*.patch
    - name: Download source fonts
      run: |
        chmod +x download-source-fonts.sh
        ./download-source-fonts.sh
    - name: Install PIP
      run: sudo apt install python-pip -y
    - name: Install configparser
      run: pip install configparser
    - name: Extract additional powerline glyphs
      run: fontforge -lang=ff -script extract-extra-glyphs
    - name: Prepare Cascadia Code font file
      run: |
        mkdir prepared
        fontforge prepare-font --input ttf/CascadiaCodePL.ttf --output prepared/CascadiaCodePL.ttf
        fontforge prepare-font --input ttf/CascadiaMonoPL.ttf --output prepared/CascadiaMonoPL.ttf
    - name: Build Powerline
      run: |
        ./do_generate 01 --powerline --mono CascadiaCodePL-Regular.ttf            DelugiaPowerline.ttf                        "Delugia PL"                   "Regular"
        ./do_generate 02 --powerline --mono CascadiaCodePL-Bold.ttf               DelugiaPowerline-Bold.ttf                   "Delugia PL"                   "Bold"
        ./do_generate 03 --powerline --mono CascadiaCodePL-Light.ttf              DelugiaPowerline-Light.ttf                  "Delugia PL Light"             ""
        ./do_generate 04 --powerline --mono CascadiaCodePLItalic-Italic.ttf       DelugiaPowerlineItalic-Italic.ttf           "Delugia PL Italic"            "Italic"
        ./do_generate 05 --powerline --mono CascadiaCodePLItalic-BoldItalic.ttf   DelugiaPowerlineItalic-BoldItalic.ttf       "Delugia PL Italic"            "Bold Italic"
        ./do_generate 06 --powerline --mono CascadiaCodePLItalic-LightItalic.ttf  DelugiaPowerlineItalic-LightItalic.ttf      "Delugia PL Italic Light"      "Italic"
        ./do_generate 11 --powerline --mono CascadiaMonoPL-Regular.ttf            DelugiaMonoPowerline.ttf                    "Delugia PL Mono"              "Regular"
        ./do_generate 12 --powerline --mono CascadiaMonoPL-Bold.ttf               DelugiaMonoPowerline-Bold.ttf               "Delugia PL Mono"              "Bold"
        ./do_generate 13 --powerline --mono CascadiaMonoPL-Light.ttf              DelugiaMonoPowerline-Light.ttf              "Delugia PL Mono Light"        ""
        ./do_generate 14 --powerline --mono CascadiaMonoPLItalic-Italic.ttf       DelugiaMonoPowerlineItalic-Italic.ttf       "Delugia PL Mono Italic"       "Italic"
        ./do_generate 15 --powerline --mono CascadiaMonoPLItalic-BoldItalic.ttf   DelugiaMonoPowerlineItalic-BoldItalic.ttf   "Delugia PL Mono Italic"       "Bold Italic"
        ./do_generate 16 --powerline --mono CascadiaCodePLItalic-LightItalic.ttf  DelugiaMonoPowerlineItalic-LightItalic.ttf  "Delugia PL Mono Italic Light" "Italic"
        mkdir delugia-powerline
        mv Delugia*ttf delugia-powerline
        zip delugia-powerline.zip delugia-powerline/*
    - name: Build Complete
      run: |
        ./do_generate 21 -c --mono CascadiaCodePL-Regular.ttf            DelugiaComplete.ttf                        "Delugia"                   "Regular"
        ./do_generate 22 -c --mono CascadiaCodePL-Bold.ttf               DelugiaComplete-Bold.ttf                   "Delugia"                   "Bold"
        ./do_generate 23 -c --mono CascadiaCodePL-Light.ttf              DelugiaComplete-Light.ttf                  "Delugia Light"             ""
        ./do_generate 24 -c --mono CascadiaCodePLItalic-Italic.ttf       DelugiaCompleteItalic-Italic.ttf           "Delugia Italic"            "Italic"
        ./do_generate 25 -c --mono CascadiaCodePLItalic-BoldItalic.ttf   DelugiaCompleteItalic-BoldItalic.ttf       "Delugia Italic"            "Bold Italic"
        ./do_generate 26 -c --mono CascadiaCodePLItalic-LightItalic.ttf  DelugiaCompleteItalic-LightItalic.ttf      "Delugia Italic Light"      "Italic"
        ./do_generate 31 -c --mono CascadiaMonoPL-Regular.ttf            DelugiaMonoComplete.ttf                    "Delugia Mono"              "Regular"
        ./do_generate 32 -c --mono CascadiaMonoPL-Bold.ttf               DelugiaMonoComplete-Bold.ttf               "Delugia Mono"              "Bold"
        ./do_generate 33 -c --mono CascadiaMonoPL-Light.ttf              DelugiaMonoComplete-Light.ttf              "Delugia Mono Light"        ""
        ./do_generate 34 -c --mono CascadiaMonoPLItalic-Italic.ttf       DelugiaMonoCompleteItalic-Italic.ttf       "Delugia Mono Italic"       "Italic"
        ./do_generate 35 -c --mono CascadiaMonoPLItalic-BoldItalic.ttf   DelugiaMonoCompleteItalic-BoldItalic.ttf   "Delugia Mono Italic"       "Bold Italic"
        ./do_generate 36 -c --mono CascadiaCodePLItalic-LightItalic.ttf  DelugiaMonoCompleteItalic-LightItalic.ttf  "Delugia Mono Italic Light" "Italic"
        mkdir delugia-complete
        mv Delugia*ttf delugia-complete
        zip delugia-complete.zip delugia-complete/*
    - name: Build Book Complete
      run: |
        ./do_generate 41 -c -c CascadiaCodePL-Regular.ttf            DelugiaBook.ttf                    "Delugia Book"              "Regular"
        ./do_generate 42 -c -c CascadiaCodePL-Bold.ttf               DelugiaBook-Bold.ttf               "Delugia Book"              "Bold"
        ./do_generate 43 -c -c CascadiaCodePL-Light.ttf              DelugiaBook-Light.ttf              "Delugia Book Light"        ""
        ./do_generate 44 -c -c CascadiaCodePLItalic-Italic.ttf       DelugiaBookItalic-Italic.ttf       "Delugia Book Italic"       "Italic"
        ./do_generate 45 -c -c CascadiaCodePLItalic-BoldItalic.ttf   DelugiaBookItalic-BoldItalic.ttf   "Delugia Book Italic"       "Bold Italic"
        ./do_generate 46 -c -c CascadiaCodePLItalic-LightItalic.ttf  DelugiaBookItalic-LightItalic.ttf  "Delugia Book Italic Light" "Italic"
        mkdir delugia-book
        mv Delugia*ttf delugia-book
        zip delugia-book.zip delugia-book/*
    - name: Check for preexisting glyphs
      run: |
        grep 'Found existing' process*.log
    - uses: actions/upload-artifact@master
      with:
        name: Delugia Powerline
        path: "delugia-powerline"
    - uses: actions/upload-artifact@master
      with:
        name: Delugia Complete
        path: "delugia-complete"
    - uses: actions/upload-artifact@master
      with:
        name: Delugia Book
        path: "delugia-book"

    # Release part
    - name: Create tag
      if: ${{ github.event_name != 'pull_request' && !startsWith(github.ref, 'refs/tags/') && needs.check-for-new-cascadia.outputs.tag_exists != 'true' }}
      uses: actions/github-script@v3
      with:
        github-token: ${{ github.token }}
        script: |
          const tagName = "${{ needs.check-for-new-cascadia.outputs.tag_name }}";

          const createdTag = await github.git.createTag({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag: tagName,
            message: `Bump Cascadia version to ${tagName}`,
            object: context.sha,
            type: "commit"
          })
          
          github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tagName}`,
              sha: createdTag.data.sha
          })
    - name: Get tag name
      id: get_tag_name
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: battila7/get-version-action@v2
    - name: Release
      uses: softprops/action-gh-release@v1
      if: ${{ github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/') || needs.check-for-new-cascadia.outputs.tag_exists != 'true') }}
      with:
        tag_name: ${{ startsWith(github.ref, 'refs/tags/') && steps.get_tag_name.outputs.version || needs.check-for-new-cascadia.outputs.tag_name }}
        files: |
          delugia-powerline.zip
          delugia-complete.zip
          delugia-book.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
